version: '3.3'

services:
      
  php:
    build:
      context: ./php-utils/
    restart: always
    command: "php -S 0.0.0.0:8080 -t /srv"
    volumes:
      - "./php-utils/php.ini:/etc/php/php.ini"
      - "./web:/srv"
    ports:
      - "8080:8080"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
